# Generated by Django 5.2.9 on 2026-01-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_user_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Temporary User Password'),
        ),
    ]
